# Generated by Django 3.2.8 on 2021-10-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('pass1', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=4000)),
                ('regdate', models.DateTimeField()),
                ('readcnt', models.IntegerField(default=0)),
                ('file1', models.CharField(max_length=100)),
            ],
        ),
    ]
